#!/bin/bash

set -e

export NODE_ENV=production
export PLAUSIBLE_API=https://mirrorwarp.github.io/api/event
export PLAUSIBLE_DOMAIN=mirrorwarp.github.io

pushd ~/scratch-gui
npm run build
date > build/date.txt
popd

echo Build complete.
